version: '3.7'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: ./
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
