version: '3.7'

services:
  db_test:
    image: postgres
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  web:
    build: ./
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file:
      - ./.env.test
    depends_on:
      - db_test
    command: bash -c 'while !</dev/tcp/db_test/5432; do sleep 1; done;
      python /usr/src/app/manage.py db migrate;python manage.py db upgrade;py.test '
