"""empty message

Revision ID: 4068e2886565
Revises: 
Create Date: 2020-09-01 01:53:24.529027

"""
from alembic import op
import sqlalchemy as sa
from src.models import ChoiceType
from src import constants
# revision identifiers, used by Alembic.
revision = '4068e2886565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DID',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('monthyPrice', sa.Float(), nullable=False),
    sa.Column('setupPrice', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('saleDate', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('role', ChoiceType(choices=constants.ROLES_TYPE), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('DID')
    # ### end Alembic commands ###
